ge_parc:
    resource: "@GeParcBundle/Resources/config/routing.yml"
    prefix:   /

ppe:
    resource: "@PpeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
